### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by vahid45** [yagasoft/DynamicsCrm-NotificationCentre#1]
Hi
How can I install solution? The solution folder is not complete dynamics CRM solution?

**Comment by yagasoft** [comment]
@vahid45 
Please follow the steps on this page:
https://github.com/yagasoft/DynamicsCrm-NotificationCentre/releases/tag/v3.1.1.1

You have to install the Base and Log solutions first.

**Comment by vahid45** [comment]
Thank you for replying
I installed every solution but no notification appeared when I created and published a notification message.

**Comment by vahid45** [comment]
and my CRM is v9 on-premise

**Comment by yagasoft** [comment]
Make sure you are using the classic interface (will migrate to UCI soon), create a record in the 'ldv_notificationscentreconfig' entity for your user (will create a guide soon), and finally, assign the Notification security roles to your user.

I created this solution as an experiment, and I didn't put the same effort into the documentation as in other, more frequently used tools/solutions. I am planning on doing it though, and I also have the code finished for UCI, but it was done by someone else, and I need to review it first. If you would like me to send you that code raw, you can review it and integrate it on your machine.

**Comment by yagasoft** [comment]
@vahid45 
I have added the v9 UCI solution to the 'Releases' page.

**Comment by vahid45** [comment]
I used classic view and i created ldv_notificationscentreconfig record but I could`n find any button for your notification.
![Untitled](https://user-images.githubusercontent.com/13600182/93660153-366b6100-fa61-11ea-9201-33bcec9b5603.png)

**Comment by vahid45** [comment]
Can I have your personal email? this is my email : mrvahid.samimi@gmail.com

**Comment by yagasoft** [comment]
I have sent you an email just now. Please let me know when you receive it.

**Comment by Mehran16007** [comment]
@yagasoft  Please send me the instruction for installing this solution.
Thanks.

**Comment by yagasoft** [comment]
@Mehran16007 
I started up a machine, will investigate the issue today and let you know.

**Comment by Mehran16007** [comment]
Thank you.
But i don't know how to install from the begging. may you please help me step by step. 
is this solution show the activity like email task appointment or just show the CRM system notification ?

**Comment by yagasoft** [comment]
Issues fixed and usage steps added to README.
