### ISSUE TITLE
Got a problem with create of generic configuration 

### ISSUE THREAD

**Issue by Mehran16007** [yagasoft/DynamicsCrm-NotificationCentre#4]
Hi, 
What are these fields and what should i fill them with?

Row Url Template
Organization base url 
Escalation user
default calendar 
What should i fill them with? and how can i set notification for a user when create a task for him/her....?

**Comment by yagasoft** [comment]
@Mehran16007 
Kindly, reserve 'issues' for problems with the system. I would greatly appreciate moving this discussion to Gitter.
https://gitter.im/yagasoft/DynamicsCrm-NotificationCentre?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
